<?php

namespace AppPhotoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends EntityRepository
{
    public function findAllActive() {
        $qb = $this->createQueryBuilder('g');
        $qb->where('g.toGuessImage <> :value')
            ->setParameter('value', null);
        return $qb->getQuery()
            ->getResult();
    }
}
