app_photo:
    resource: "@AppPhotoBundle/Controller/"
    type:     annotation
    prefix:   /

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

# app/config/routing.yml
easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/"
    type:     annotation
    prefix:   /index

