<?php

namespace AppPhotoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GamesAnswersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GamesAnswersRepository extends EntityRepository
{
}
