<?php

namespace AppPhotoBundle\Repository;

/**
 * GameAnswerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameAnswerRepository extends \Doctrine\ORM\EntityRepository
{
}
